# Generated by Django 2.2a1 on 2019-02-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='alumnee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=20, null=True)),
                ('PersonalDescription', models.TextField(max_length=200, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('image', models.FileField(max_length=200, null=True, upload_to='')),
                ('email', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('adress', models.CharField(max_length=30, null=True)),
                ('HighestEducation', models.CharField(max_length=30, null=True)),
                ('graduationYear', models.CharField(max_length=30, null=True)),
                ('Employed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100, null=True)),
                ('projectDescription', models.TextField(max_length=200, null=True)),
                ('projectScreenshot', models.CharField(max_length=200, null=True)),
                ('projectlink', models.CharField(max_length=200, null=True)),
                ('certificationImage', models.CharField(max_length=200, null=True)),
                ('alumnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnee.alumnee')),
            ],
        ),
        migrations.CreateModel(
            name='internshipExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('roles', models.TextField(max_length=100, null=True)),
                ('alumnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnee.alumnee')),
            ],
        ),
    ]
