# Generated by Django 2.2a1 on 2019-02-18 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100, null=True)),
                ('level', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('grade', models.CharField(max_length=100, null=True)),
                ('alumnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnee.alumnee')),
            ],
        ),
    ]
