# Generated by Django 2.1 on 2019-02-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnee', '0002_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='internshipExperience',
            new_name='internship_experience',
        ),
    ]
