# Generated by Django 2.1 on 2019-02-19 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnee', '0003_auto_20190219_2014'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='internship_experience',
            new_name='internship',
        ),
    ]
